### ISSUE TITLE
Need help installing channeltabs

### ISSUE THREAD

**Issue by xITmasterx** [ActuallyTheSun/vendetta-plugins#1]
Sorry for asking you this in a different repository, will delete this after you respond. 

I want to install channeltabs into Vencord, problem is that I can't seem to find a way to do so without installing it in a dev manner. How do I go about installing such a plugin without dealing with the Dev Vencord method? I really need to use it.

Thanks in advance!

**Comment by sunnniee** [comment]
short answer, you can't

unlike other client mods, vencord doesn't provide a native way to add third party plugins, so the only way to add your own plugin is using a dev install.

even if you could just drop the plugin's files in, it still wouldn't work, as the plugin makes some modifications to vencord itself to allow it to work, so the only actual way to get it running is to clone the vencord fork and use that. the plugin wasn't made with ease of install in mind, as it's expected for it to eventually be added into actual vencord

**Comment by xITmasterx** [comment]
When is it going to be added into vencord though? I've seen a bunch of push request passed around with updates and everything is in the green, just needed final approval from the author of Vencord, correct?

**Comment by sunnniee** [comment]
it's gonna be added when ven gets around to it, which given the backlog of open pr's will likely be a while. can't do anything about that other than wait and occasionally request a review

**Comment by xITmasterx** [comment]
Will do, thanks for the info, and I do hope that Ven would get around it. Closing this.
